---
title: "Question 1"
format: html
editor: visual
---

```{r}
install.packages(c("tidyverse", "datasauRus"))
library(tidyverse)
library(datasauRus)
datasaurus_dozen %>%
  count(dataset)

```

------------------------------------------------------------------------

---
title: "Question 2"
format: html
editor: visual
---

```{r}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) + geom_point()
dino_data %>%
  summarize(r = cor(x,y))


```

------------------------------------------------------------------------

---
title: "Question 3"
format: html
editor: visual
---

```{r}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) + geom_point()
star_data %>%
  summarize(r = cor(x,y))
```

------------------------------------------------------------------------

---
title: "Question 4"
format: html
editor: visual
---

```{r}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) + geom_point()
dino_data %>%
  summarize(r = cor(x,y))
```

------------------------------------------------------------------------

---
title: "Question 5"
format: html
editor: visual
---

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset)) + geom_point() + facet_wrap(~dataset, ncol = 3) + theme(legend.position = "none")
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y))
  
```

## 
